name: aiyanaalexander
favicon: null
layout_spectrum: 0.7952506945002824
typography_spectrum: 0.5276548098772764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9505508437287062
  lightness: 0.47901023807935417
  saturation: 0.10342297167517245
  rhythmicContrast: 0.7228198715019971
purpose: []
