name: aiyanaalexander
favicon: null
layout_spectrum: 0.1629
typography_spectrum: 0.12295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff00ff'
    - '#040006'
    - '#ff8eff'
    - '#fefefe'
    - '#40a8c5'
  brandStrength: 0.125
  lightness: 0.47901023807935417
  saturation: 0.10342297167517245
  rhythmicContrast: 0.7228198715019971
purpose: []
